### ISSUE TITLE
在使用过程中会有报错，查看依赖的commander 已经安装了。

### ISSUE THREAD

**Issue by crazyit** [empjs/emp#349]
报错平台：window 11
报错截图：
![image](https://github.com/efoxTeam/emp/assets/6240481/54ccfe2d-0e07-4850-b879-1e031ce50265)
报错的项目地址：https://github.com/yylive/YYEVA-Web/tree/main/projects/es5-demo
期望：麻烦开发组看到issue后，在window项目尝试运行项目地址的项目，目前是一直报错。提示commander未声明，实际项目中已经声明

**Comment by ckken** [comment]
我们一直在用是没问题的 请问有没有用 pnpm 再根目录安装

**Comment by crazyit** [comment]
谢谢百忙之中回复，pnpm 再根目录尝试过执行安装，我是在跑这个项目 https://github.com/yylive/YYEVA-Web.我后面在win11 Ubuntu子系统没有遇到该问题，所以一直都在用ubuntu系统来编译了。
