### ISSUE TITLE
在库中使用vue插槽会使currentRenderingInstance为null

### ISSUE THREAD

**Issue by 17722970136** [empjs/emp#365]
runtime-core.esm-bundler.js:2943 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js:2943:1)
    at Proxy.render (index.vue:7:13)
    at renderComponentRoot (runtime-core.esm-bundler.js:877:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6004:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:1)
    at instance.update (runtime-core.esm-bundler.js:6135:1)
    at setupRenderEffect (runtime-core.esm-bundler.js:6145:1)
    at mountComponent (runtime-core.esm-bundler.js:5913:1)
    at processComponent (runtime-core.esm-bundler.js:5867:1)
    at patch (runtime-core.esm-bundler.js:5335:1)
### a 组件预留了<slot>就会报错
exposes a 组件
```a组件  
<template>
    <div class="p-container">
        <div class="p-header">
            {{ name }}
        </div>
        <div class="p-main">
            <slot></slot>
        </div>
    </div>
</template>
<script lang="ts" setup>
const name = 'APP_LIB_Container';
</script>

```

```b 组件
<template>
    <ContainerPage>
            1223
    </ContainerPage>
</template>
<script lang="ts" setup>
import { ContainerPage } from 'UnifyAppLib/busComp';  // 通过empShare.remote 引入
</script>
```

**Comment by 17722970136** [comment]
const { defineConfig } = require('@efox/emp');
const path = require('path');
const vue3 = require('@efox/plugin-vue-3');
const appTitle = require('./package.json').title;
const exposes = require('./expose-config');
const remotes = require('./remote-config');

module.exports = defineConfig({
  plugins: [vue3],
  appEntry: 'main.ts',

  empShare: {
    name: 'UnifyPortal',
    filename: 'emp.js',
    remotes: {
'UnifyAppLib': 'UnifyAppLib@http://localhost:8083/emp.js',
},
  },
})

**Comment by 17722970136** [comment]
两个项目使用的都是 const vue3 = require('@efox/plugin-vue-3');

**Comment by ckken** [comment]
请问有仓库吗

**Comment by 17722970136** [comment]
这个测试仓库 随便玩
https://github.com/17722970136/emp-issue.git


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "empjs/emp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月7日(星期四) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [empjs/emp] 在库中使用vue插槽会使currentRenderingInstance为null (Issue #365)





 
请问有仓库吗

**Comment by neversleeppy** [comment]
可以问下你怎么解决的嘛？我也遇到这个问题了
