### ISSUE TITLE
vue-tsc: 1.8.27(typescript@4.9.5) 没有__internal__ 字段

### ISSUE THREAD

**Issue by 17722970136** [empjs/emp#366]
"@efox/emp": "2.7.1"
packages/emp/src/dts/getVueTsService.ts
vue-tsc: 1.8.27(typescript@4.9.5) 没有__internal__ 字段 执行emp  build -t会报错，调整如下正常编译
```js
  const service = program.__vue.languageService.__internal__.languageService
改成 ：
  const service = program.__vue.languageService
```

**Comment by 17722970136** [comment]
"@efox/emp": "2.7.1"

**Comment by ckken** [comment]
是老项目还是？目前3.0冲刺阶段 如果新项目可以先尝试3.0
