### ISSUE TITLE
按文档说明, EMP3 demo mf-host 不能运行

### ISSUE THREAD

**Issue by yanyim** [empjs/emp#375]
启动 mf-host
页面错误信息:
Uncaught ReferenceError: EmpShareLib is not defined
    at @module-federation/runtime (http://localhost:8081/js/index.b669f007.js:7962:18)
    at __webpack_require__ (http://localhost:8081/js/index.b669f007.js:8312:21)
    at fn (http://localhost:8081/js/index.b669f007.js:8508:10)
    at ../../node_modules/.pnpm/@module-federation+webpack-bundler-runtime@0.1.19/node_modules/@module-federation/webpack-bundler-runtime/dist/index.cjs.js (http://localhost:8081/js/index.b669f007.js:30:15)
    at __webpack_require__ (http://localhost:8081/js/index.b669f007.js:8312:21)
    at fn (http://localhost:8081/js/index.b669f007.js:8508:10)
    at data:text/javascript,import __module_federation_bundler_runtime__ from "E:\\laboratory\\xuesop\\node_modules\\.pnpm\\@module-federation+webpack-bundler-runtime@0.1.19\\node_modules\\@module-federation\\webpack-bundler-runtime\\dist\\index.cjs.js"
const __module_federation_runtime_plugins__ = []
const __module_federation_remote_infos__ = {}
const __module_federation_container_name__ = "mfHost"
    if ((__webpack_require__.initializeSharingData ||
        __webpack_require__.initializeExposesData) &&
        __webpack_require__.federation) {
        const override = (obj, key, value) => {
            if (!obj)
                return;
            if (obj[key])
                obj[key] = value;
        };
        const merge = (obj, key, fn) => {
            const value = fn();
            if (Array.isArray(value)) {
                obj[key] ??= [];
                obj[key].push(...value);
            }
            else if (typeof value === "object" && value !== null) {
                obj[key] ??= {};
                Object.assign(obj[key], value);
            }
        };
        const early = (obj, key, initial) => {
            obj[key] ??= initial();
        };
        const remotesLoadingChunkMapping = __webpack_require__.remotesLoadingData?.chunkMapping ?? {};
        const remotesLoadingModuleIdToRemoteDataMapping = __webpack_require__.remotesLoadingData?.moduleIdToRemoteDataMapping ?? {};
        const initializeSharingScopeToInitDataMapping = __webpack_require__.initializeSharingData?.scopeToSharingDataMapping ??
            {};
        const consumesLoadingChunkMapping = __webpack_require__.consumesLoadingData?.chunkMapping ?? {};
        const consumesLoadingModuleToConsumeDataMapping = __webpack_require__.consumesLoadingData?.moduleIdToConsumeDataMapping ??
            {};
        const consumesLoadinginstalledModules = {};
        const initializeSharingInitPromises = [];
        const initializeSharingInitTokens = [];
        const containerShareScope = __webpack_require__.initializeExposesData?.shareScope;
        for (const key in __module_federation_bundler_runtime__) {
            __webpack_require__.federation[key] =
                __module_federation_bundler_runtime__[key];
        }
        early(__webpack_require__.federation, "consumesLoadingModuleToHandlerMapping", () => {
            const consumesLoadingModuleToHandlerMapping = {};
            for (let [moduleId, data] of Object.entries(consumesLoadingModuleToConsumeDataMapping)) {
                consumesLoadingModuleToHandlerMapping[moduleId] = {
                    getter: data.fallback,
                    shareInfo: {
                        shareConfig: {
                            fixedDependencies: false,
                            requiredVersion: data.requiredVersion,
                            strictVersion: data.strictVersion,
                            singleton: data.singleton,
                            eager: data.eager
                        },
                        scope: [data.shareScope]
                    },
                    shareKey: data.shareKey
                };
            }
            return consumesLoadingModuleToHandlerMapping;
        });
        early(__webpack_require__.federation, "initOptions", () => ({}));
        early(__webpack_require__.federation.initOptions, "name", () => __module_federation_container_name__);
        early(__webpack_require__.federation.initOptions, "shared", () => {
            const shared = {};
            for (let [scope, stages] of Object.entries(initializeSharingScopeToInitDataMapping)) {
                for (let stage of stages) {
                    if (typeof stage === "object" && stage !== null) {
                        const { name, version, factory, eager } = stage;
                        const options = { version, scope: [scope], get: factory };
                        if (shared[name]) {
                            shared[name].push(options);
                        }
                        else {
                            shared[name] = [options];
                        }
                    }
                }
            }
            return shared;
        });

**Comment by SiyuQian** [comment]
碰到了一样的问题
```
pnpm --version
9.1.2

node --version
v20.11.0
```
Install时没有任何异常, 在`projects/mf-host` folder下面运行`pnpm dev`也没有任何报错

**Comment by ckken** [comment]
能否提供 demo仓库

**Comment by SiyuQian** [comment]
@ckken 你好 谢谢回复。就是官方提供的repo哦。没有改东西，只是尝试运行
```
// 1. cd projects/mf-host
// 2. pnpm dev
// 3. access http://localhost:8001/
```

**Comment by yanyim** [comment]
> @ckken 你好 谢谢回复。就是官方提供的repo哦。没有改东西，只是尝试运行
> 
> ```
> // 1. cd projects/mf-host
> // 2. pnpm dev
> // 3. access http://localhost:8001/
> ```
> 
> 不知道楼主的问题跟我的复现步骤是不是一样的。

**Comment by yanyim** [comment]
> @ckken 你好 谢谢回复。就是官方提供的repo哦。没有改东西，只是尝试运行
> 
> ```
> // 1. cd projects/mf-host
> // 2. pnpm dev
> // 3. access http://localhost:8001/
> ```
> 
> 不知道楼主的问题跟我的复现步骤是不是一样的。

我和你一样的，没有改过任何东西，只是尝试运行

**Comment by ckken** [comment]
@ron0115

**Comment by doerme** [comment]
updated now [7680552](768055229839ee52b77b970e464ec43b68b84902)

**Comment by doerme** [comment]
updated now [7680552](768055229839ee52b77b970e464ec43b68b84902)
