### ISSUE TITLE
端口占用，启动不了，没有自动切换到下一个端口的功能吗？

### ISSUE THREAD

**Issue by wangcylive** [empjs/emp#377]
我有两个项目，一个启动占用了 8800端口，启动第二个项目会提示端口占用

emp.config.js
`server: {
        https: true,
        headers: {'Access-Control-Allow-Origin': '*'},
        client: {
          overlay: false,
        },
},`

环境：
Node@20
EMP@3.1.13
![Untitled tinify](https://github.com/user-attachments/assets/39f756ca-7876-452a-9819-b1b6bf15ac9f)

**Comment by ckken** [comment]
fixed it https://www.npmjs.com/package/@empjs/cli/v/3.2.5
